name: down-bot

on:
  workflow_dispatch:

jobs:
  run-down-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Simular tarefa do workflow
        run: |
          echo "Iniciando o Down Bot..."
          sleep 300 
          echo "Down Bot concluído."
