name: down-bot  # Esse bot é responsável por rodar os scripts de download dos frames 

on:
    workflow_dispatch:

concurrency:  # previne que o workflow seja executado em paralelo
  group: down-bot-${{ github.ref }}
  cancel-in-progress: false

jobs:
  
  run-down-bot:
    runs-on: ubuntu-latest

    env:
      FB_TOKEN: ${{ secrets.FB_TOKEN }}
      IMG_TOKEN: ${{ secrets.IMG_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.9
          architecture: x64 
      
      - name: Instalar Dependências
        run: |
          python -m pip install -r requirements.txt

      - name: Executar script Python
        run: python main.py  # Saída e erros serão exibidos em tempo real

      - name: Update arquivos
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "updated"
          repository: .
          file_pattern: replyed_ids.txt
